# Generated by Django 5.1.5 on 2025-02-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='defeito_cliente',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('C', 'Criado'), ('F', 'Finalizado'), ('E', 'Entregue')], default='C', max_length=1, verbose_name='Status do Serviço'),
        ),
    ]
