# Generated by Django 5.1.5 on 2025-02-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_servico_defeito_cliente_alter_servico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
