# Generated by Django 5.1.5 on 2025-02-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_servico_data_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
