# Generated by Django 5.1.5 on 2025-02-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_remove_servico_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopagamento',
            name='tipo',
            field=models.CharField(choices=[('P', 'PIX'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('D', 'Dinheiro')], max_length=2, unique=True),
        ),
    ]
