# Generated by Django 5.1.5 on 2025-03-16 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_tipopagamento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servico',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipopagamento',
            name='tipo',
            field=models.CharField(choices=[('P', 'PIX'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('D', 'Dinheiro'), ('C', 'Criptomoeda')], max_length=2, unique=True),
        ),
    ]
